{
 "title": "bilirec / 累計用量",
 "description": "選定時間範圍內的合計：彈幕、直播流落盤量、錄製時長、錄製次數。房間多選，All 看全站。落盤量是寫入器 Write() 實際寫出的位元組，不是主機 df。明細表另有讀入量（TCP）。錄製時長使用 VictoriaMetrics integrate()。",
 "tags": [ "bilirec" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "資料源", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(bilirec_active_recordings, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(bilirec_active_recordings{job=~\"$job\"}, instance)"
   },
   {
    "name": "room_id",
    "label": "房間",
    "query": "query_result(max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))"
   },
   { "name": "topk", "label": "Top N", "query": "5,10,20,50" }
  ]
 },
 "panels": [
  { "title": "本區間合計", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "總落盤量",
   "type": "stat",
   "description": "寫入器 Write() 實際寫出的位元組合計（含切檔）。通常略小於或接近最終檔案大小。",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bilirec_room_stream_bytes_written_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "落盤"
    }
   ]
  },
  {
   "title": "總錄製時長",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(integrate(bilirec_room_recording_active{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "錄製"
    }
   ]
  },
  {
   "title": "總彈幕",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "彈幕"
    }
   ]
  },
  {
   "title": "錄製次數",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bilirec_room_recording_sessions_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "次數"
    }
   ]
  },
  { "title": "對照", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "彈幕實寫條數",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) - (sum(increase(bilirec_danmaku_messages_dropped_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0))) or vector(0)",
     "legendFormat": "實寫"
    }
   ]
  },
  {
   "title": "彈幕檔位元組",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bilirec_danmaku_bytes_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "彈幕檔"
    }
   ]
  },
  {
   "title": "開播時長",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(integrate(bilirec_room_live_status{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "開播"
    }
   ]
  },
  { "title": "各房排名", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "各房落盤量（Top N）",
   "type": "bargauge",
   "description": "按寫入器實際寫出的位元組排名，接近各房間占用的磁碟空間。",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk, sum by (room_id) (increase(bilirec_room_stream_bytes_written_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{uname}} ({{room_id}})"
    }
   ]
  },
  {
   "title": "各房錄製時長（Top N）",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk, sum by (room_id) (integrate(bilirec_room_recording_active{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{uname}} ({{room_id}})"
    }
   ]
  },
  {
   "title": "各房彈幕條數（Top N）",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk, sum by (room_id) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{uname}} ({{room_id}})"
    }
   ]
  },
  {
   "title": "各房錄製次數（Top N）",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk, sum by (room_id) (increase(bilirec_room_recording_sessions_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{uname}} ({{room_id}})"
    }
   ]
  },
  { "title": "每房明細", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "各房合計",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (room_id) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (increase(bilirec_room_stream_bytes_written_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (integrate(bilirec_room_recording_active{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (increase(bilirec_room_recording_sessions_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "(sum by (room_id) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) - on(room_id) (sum by (room_id) (increase(bilirec_danmaku_messages_dropped_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or on(room_id) sum by (room_id) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * 0)) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (integrate(bilirec_room_live_status{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (increase(bilirec_room_stream_bytes_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "彈幕類型",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (event_type) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  }
 ]
}