{
 "title": "bilirec / 累计用量",
 "description": "选定时间范围内的合计：弹幕、直播流落盘量、录制时长、录制次数。房间多选，All 看全站。落盘量是写入器 Write() 实际写出的字节，不是主机 df。明细表另有读入量（TCP）。录制时长使用 VictoriaMetrics integrate()。",
 "tags": [ "bilirec" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(bilirec_active_recordings, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(bilirec_active_recordings{job=~\"$job\"}, instance)"
   },
   {
    "name": "room_id",
    "label": "房间",
    "query": "query_result(max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))"
   },
   { "name": "topk", "label": "Top N", "query": "5,10,20,50" }
  ]
 },
 "panels": [
  { "title": "本区间合计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总落盘量",
   "type": "stat",
   "description": "写入器 Write() 实际写出的字节合计（含切档）。通常略小于或接近最终文件大小。",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bilirec_room_stream_bytes_written_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "落盘"
    }
   ]
  },
  {
   "title": "总录制时长",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(integrate(bilirec_room_recording_active{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "录制"
    }
   ]
  },
  {
   "title": "总弹幕",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "弹幕"
    }
   ]
  },
  {
   "title": "录制次数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bilirec_room_recording_sessions_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "次数"
    }
   ]
  },
  { "title": "对照", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "弹幕实写条数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) - (sum(increase(bilirec_danmaku_messages_dropped_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0))) or vector(0)",
     "legendFormat": "实写"
    }
   ]
  },
  {
   "title": "弹幕文件字节",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bilirec_danmaku_bytes_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "弹幕文件"
    }
   ]
  },
  {
   "title": "开播时长",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(integrate(bilirec_room_live_status{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or vector(0)",
     "legendFormat": "开播"
    }
   ]
  },
  { "title": "各房排名", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "各房落盘量（Top N）",
   "type": "bargauge",
   "description": "按写入器实际写出的字节排名，接近各房间占用的磁盘空间。",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk, sum by (room_id) (increase(bilirec_room_stream_bytes_written_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{uname}} ({{room_id}})"
    }
   ]
  },
  {
   "title": "各房录制时长（Top N）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk, sum by (room_id) (integrate(bilirec_room_recording_active{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{uname}} ({{room_id}})"
    }
   ]
  },
  {
   "title": "各房弹幕条数（Top N）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk, sum by (room_id) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{uname}} ({{room_id}})"
    }
   ]
  },
  {
   "title": "各房录制次数（Top N）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($topk, sum by (room_id) (increase(bilirec_room_recording_sessions_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{uname}} ({{room_id}})"
    }
   ]
  },
  { "title": "每房明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "各房合计",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (room_id) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (increase(bilirec_room_stream_bytes_written_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (integrate(bilirec_room_recording_active{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (increase(bilirec_room_recording_sessions_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "(sum by (room_id) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) - on(room_id) (sum by (room_id) (increase(bilirec_danmaku_messages_dropped_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) or on(room_id) sum by (room_id) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * 0)) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (integrate(bilirec_room_live_status{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (room_id) (increase(bilirec_room_stream_bytes_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range])) * on(room_id) group_left(uname) max by (room_id, uname) (bilirec_room_info{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "弹幕类型",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (event_type) (increase(bilirec_danmaku_messages_total{job=~\"$job\", instance=~\"$instance\", room_id=~\"$room_id\"}[$__range]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  }
 ]
}